packages:
  base_components: !include packages/esp_home_components.yaml

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m
  build_path: "./build/${device_name}"

# Status LED inv on GPIO2

status_led:
  pin:
    number: 01
    inverted: True

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO15
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO13
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO12
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: white1_output
    pin: GPIO4
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: white2_output
    pin: GPIO14
    frequency: 1000 Hz

light:
  - platform: rgbw
    id: light_1
    name: "${pretty_name}"
    restore_mode: ${light_restore_mode}
    red: red_output
    green: green_output
    blue: blue_output
    cold_white: white1_output
    warm_white: white2_output
    effects:
      - lambda:
          name: Rainbowy
          update_interval: 4s
          lambda: |-
            static int state = 0;
            auto call = id(light_1).turn_on();
            call.set_transition_length(4000);
            if (state == 0) {
              call.set_rgb(1.0, 0.0, 0.0);
            } else if (state == 1) {
              call.set_rgb(1.0, 1.0, 0.0);
            } else if (state == 2) {
              call.set_rgb(0.0, 1.0, 0.0);
            } else if (state == 3) {
              call.set_rgb(0.0, 1.0, 1.0);
            } else if (state == 4) {
              call.set_rgb(0.0, 0.0, 1.0);
            } else if (state == 5) {
              call.set_rgb(1.0, 0.0, 1.0);
            }
            call.perform();
            state += 1;
            if (state == 6)
              state = 0;
      - flicker:
      - flicker:
          name: Flicker 2
          alpha: 85%
          intensity: 5.0%
      - flicker:
          name: Low Alpha
          alpha: 60%
          intensity: 1.5%
      - flicker:
          name: High Intensity
          alpha: 95%
          intensity: 20.0%
      - random: