packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "accent-led-figurines"
  pretty_name: "Accent Led Figurines"
  ui_name: "Accent Led Figurines"
  icon: "mdi:lghtbulb"
