packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-002"
  pretty_name: "Basement Light 002"
  ui_name: "Basement Light 002"
  icon: "mdi:lghtbulb"
