packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-013"
  pretty_name: "Basement Light 013"
  ui_name: "Basement Light 013"
  icon: "mdi:lghtbulb"
