packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-001"
  pretty_name: "Basement Light 001"
  ui_name: "Basement Light 001"
  icon: "mdi:lghtbulb"
