packages: 
  package: !include common/button_box_6_long_press.yaml

substitutions:
  device_name: "basement-lightswitch"
  pretty_name: "Basement Lightswitch"
  target_1: "group.basement_lights_main"
  target_2: "group.basement_lights_accent"
  target_3: "group.basement_lights_storage"