packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-004"
  pretty_name: "Basement Light 004"
  ui_name: "Basement Light 004"
  icon: "mdi:lghtbulb"
