packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-003"
  pretty_name: "Basement Light 003"
  ui_name: "Basement Light 003"
  icon: "mdi:lghtbulb"
