packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-006"
  pretty_name: "Basement Light 006"
  ui_name: "Basement Light 006"
  icon: "mdi:lghtbulb"
