packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-011"
  pretty_name: "Basement Light 011"
  ui_name: "Basement Light 011"
  icon: "mdi:lghtbulb"
