packages: 
  package: !include common/wifi_smart_life_smart_socket_eu_mini_light.yaml

substitutions:
  device_name: "basement-light-014"
  pretty_name: "Basement Light 014"
  ui_name: "Basement Light 014"
  icon: "mdi:lghtbulb"
