packages: 
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "basement-stairs-bottom-light"
  pretty_name: "Basement Stairs Bottom Lightswitch"
  ui_name: "Basement Stairs Light"
  icon: "mdi:lghtbulb"
