packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-012"
  pretty_name: "Basement Light 012"
  ui_name: "Basement Light 012"
  icon: "mdi:lghtbulb"
