packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-005"
  pretty_name: "Basement Light 005"
  ui_name: "Basement Light 005"
  icon: "mdi:lghtbulb"
