packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-007"
  pretty_name: "Basement Light 007"
  ui_name: "Basement Light 007"
  icon: "mdi:lghtbulb"
