packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-010"
  pretty_name: "Basement Light 010"
  ui_name: "Basement Light 010"
  icon: "mdi:lghtbulb"
