packages: 
  package: !include common/sonoff_basic_light.yaml

substitutions:
  device_name: "basement-light-008"
  pretty_name: "Basement Light 008"
  ui_name: "Basement Light 008"
  icon: "mdi:lghtbulb"
