packages:
  package: !include common/h801_rgbw.yaml

substitutions:
  device_name: "living-room-rgbstrip-5"
  pretty_name: "Living Room RGB strip 5"
  light_restore_mode: RESTORE_DEFAULT_OFF

# esphome:
# on_boot:
#     then:
#     - light.control:
#         id: light_1
